apiVersion: v1
kind: Service
metadata:
  name: appointments-service
  namespace: kong
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 5055
      targetPort: 5055
  selector:
    app: appointments
